language: ruby

services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=mskj/buildpack-java-builder

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t mskj/java8-builder-base:latest -f java8-builder-base.dockerfile . 
  - docker build -t mskj/java11-builder-base:latest -f java11-builder-base.dockerfile .
  - docker push mskj/java8-builder-base:latest
  - docker push mskj/java11-builder-base:latest
  - sudo apt-get install -y curl
  - curl -L $(curl -s https://api.github.com/repos/buildpacks/pack/releases/latest |grep 'browser_' |grep linux |cut -d\" -f4) --output pack.tgz
  - tar xvf pack.tgz
  - rm pack.tgz
  - ./pack create-builder ${REPO}:java8-${COMMIT} -b java8-builder.toml
  - ./pack create-builder ${REPO}:java11-${COMMIT} -b java11-builder.toml
  - rm pack
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
