language: ruby

services:
  - docker

script:
  - wget https://github.com/buildpack/pack/releases/download/v0.5.0/pack-v0.5.0-linux.tgz
  - tar xvf pack-v0.5.0-linux.tgz
  - rm pack-v0.5.0-linux.tgz
  - ./pack create-builder mskj/maven-builder:latest -b builder.toml
  - rm pack
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
