language: ruby

services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=mskj/buildpack-java-builder

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t mskj/java8-builder-base:latest -f java8-builder-base.dockerfile . 
  - docker build -t mskj/java11-builder-base:latest -f java11-builder-base.dockerfile .
  - docker push mskj/java8-builder-base:latest
  - docker push mskj/java11-builder-base:latest
  - wget https://github.com/buildpack/pack/releases/download/v0.5.0/pack-v0.5.0-linux.tgz
  - tar xvf pack-v0.5.0-linux.tgz
  - rm pack-v0.5.0-linux.tgz
  - ./pack create-builder ${REPO}:java8-${COMMIT} -b java8-builder.toml
  - ./pack create-builder ${REPO}:java11-${COMMIT} -b java11-builder.toml
  - rm pack
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
